#!/bin/ksh
################################################################################
#                   @(#)Copyright (c) 1997 William R. Quayle                   #
#                             All Rights Reserved                              #
################################################################################
#                                                                              #
# This is free software.  It comes  with absolutely  NO WARRENTY  expressed or #
# implied.                                                                     #
#                            USE AT YOUR OWN RISK!                             #
#                                                                              #
# Permission is granted to use, modify, and distribute copies of this software #
# software  provided  the following conditions are met:                        #
#                                                                              #
#      1) that that the above copyright notice and this notice                 #
#         are preserved in all copies and that due credit be given             #
#         to the author.                                                       #
#                                                                              #
#      2) that any changes to this code are clearly commented                  #
#         as such so that the author does get blamed for bugs                  #
#         other than his own.                                                  #
#                                                                              #
#      Please send copies of changes and bug-fixes to:                         #
#                                                                              #
#                             billq@technologist.com                           #
#                                                                              #
################################################################################
if [ -f /etc/defaultrouter ]
then
HOST=`hostname`
case $HOST in
zeus|thor|orion|utopia|camelot)
	route -f add default `cat /etc/defaultrouter` 1
	route add net 131.198.118.0 131.198.116.138 1
	route add net 131.198.119.0 131.198.116.138 1
	route add net 131.198.120.0 131.198.116.138 1
	route add net 131.198.121.0 131.198.116.138 1
	route add net 131.198.122.0 131.198.116.138 1
	route add net 131.198.123.0 131.198.116.138 1
	route add net 149.141.110.0 131.198.116.138 1
;;
zod)
	route -f add default `cat /etc/defaultrouter` 1
	route add net 131.198.117.0 131.198.116.138 1
	route add net 131.198.118.0 131.198.116.138 1
	route add net 131.198.119.0 131.198.116.138 1
	route add net 131.198.120.0 131.198.116.138 1
	route add net 131.198.123.0 131.198.116.138 1
	route add net 149.141.110.0 131.198.116.138 1
;;
131.198.116.111|corsair)	
	route -f add default `cat /etc/defaultrouter` 1
	route add net 131.198.117.0 131.198.116.138 1
	route add net 131.198.119.0 131.198.116.138 1
	route add net 131.198.122.0 131.198.116.138 1
	route add net 131.198.118.0 131.198.116.138 1
	route add net 131.198.123.0 131.198.116.138 1
	route add net 149.141.110.0 131.198.116.138 1
;;
*)
	SUBNET=`grep $HOST /etc/hosts|awk '{print $1}'|sed 's/131\.198\.//'|sed 's/\.[0-9]*//'|uniq`
	case $SUBNET in
	116)
		route -f add default `cat /etc/defaultrouter` 1
		route add net 131.198.117.0 131.198.116.138 1
		route add net 131.198.118.0 131.198.116.138 1
		route add net 131.198.119.0 131.198.116.138 1
		route add net 131.198.120.0 131.198.116.138 1
		route add net 131.198.122.0 131.198.116.138 1
		route add net 131.198.123.0 131.198.116.138 1
		route add net 149.141.110.0 131.198.116.138 1
	;;
	*)
		route -f add default `cat /etc/defaultrouter` 1
	;;
	esac
;;
esac
else
	/usr/etc/in.routed
fi
