#!/bin/ksh
################################################################################
#                   @(#)Copyright (c) 1996 William R. Quayle                   #
#                             All Rights Reserved                              #
################################################################################
#                                                                              #
# This is free software.  It comes  with absolutely  NO WARRENTY  expressed or #
# implied.                                                                     #
#                            USE AT YOUR OWN RISK!                             #
#                                                                              #
# Permission is granted to use, modify, and distribute copies of this software #
# software  provided  the following conditions are met:                        #
#                                                                              #
#      1) that that the above copyright notice and this notice                 #
#         are preserved in all copies and that due credit be given             #
#         to the author.                                                       #
#                                                                              #
#      2) that any changes to this code are clearly commented                  #
#         as such so that the author does get blamed for bugs                  #
#         other than his own.                                                  #
#                                                                              #
#      Please send copies of changes and bug-fixes to:                         #
#                                                                              #
#                             quayle@switch.rockwell.com                       #
#                                                                              #
################################################################################
#
# alive - check out stdin Suns to see who's up, dead, or inaccessible
#
# exit codes:
#   1 - can't even ping the sucker
#   2 - can ping, but spray fails miserably
#   3 - can ping and spray, but not rsh, the thing must be a pc or x term
#
#	usage: for i in `cat host_list` ; do alive $i ; if [ $? -eq 0 ] ; then
################################################################################
if [ $# -ne 1 ]
then
	echo "
################################################################################
#
# alive - check out stdin Suns to see who's up, dead, or inaccessible
#	usage: for i in `cat host_list` ; do alive $i ; if [ $? -eq 0 ] ; then
################################################################################
"
else
	HOST=$1
fi
ping $HOST 2 >/dev/null 2>&1
if [ $? = 0 ]
then
	spray -l 1 -c 1 $HOST >>$LOGDIR/spray.stats 2>&1
	if [ $? = 0 ]
	then
		STAT=`rsh $HOST 'sun;echo $?' 2>&1`
		if [ "$STAT" = "0" ]
		then
			exit 0
		else
			exit 3
		fi
	else
		exit 2
	fi
else
	exit 1
fi
