#!/bin/ksh
################################################################################
#                   @(#)Copyright (c) 1992 William R. Quayle                   #
#                             All Rights Reserved                              #
################################################################################
#                                                                              #
# This is free software.  It comes  with absolutely  NO WARRENTY  expressed or #
# implied.                                                                     #
#                            USE AT YOUR OWN RISK!                             #
#                                                                              #
# Permission is granted to use, modify, and distribute copies of this software #
# software  provided  the following conditions are met:                        #
#                                                                              #
#      1) that that the above copyright notice and this notice                 #
#         are preserved in all copies and that due credit be given             #
#         to the author.                                                       #
#                                                                              #
#      2) that any changes to this code are clearly commented                  #
#         as such so that the author does get blamed for bugs                  #
#         other than his own.                                                  #
#                                                                              #
#      Please send copies of changes and bug-fixes to:                         #
#                                                                              #
#                             billq@technologist.com                           #
#                                                                              #
################################################################################
#
# checkhosts - fix netgroup up to include all local machines
#
################################################################################
for j in 116 117 118 119 120 121 122 123
do
	for i in `ypcat hosts|grep "\.${j}\."|awk '{print $2}'`
	do
		NUM="`ypcat netgroup|grep -c $i`"
		if [ "$NUM" = "0" ]
		then
			echo $i not found in netgroup
		fi
	done
done
# Get netgroup entries not in hosts...
for k in 
do
	ypmatch $k hosts >/dev/null 
	ping $k 2 > /dev/null
done
