#!/bin/ksh
################################################################################
#                   @(#)Copyright (c) 1993 William R. Quayle                   #
#                             All Rights Reserved                              #
################################################################################
#                                                                              #
# This is free software.  It comes  with absolutely  NO WARRENTY  expressed or #
# implied.                                                                     #
#                            USE AT YOUR OWN RISK!                             #
#                                                                              #
# Permission is granted to use, modify, and distribute copies of this software #
# software  provided  the following conditions are met:                        #
#                                                                              #
#      1) that that the above copyright notice and this notice                 #
#         are preserved in all copies and that due credit be given             #
#         to the author.                                                       #
#                                                                              #
#      2) that any changes to this code are clearly commented                  #
#         as such so that the author does get blamed for bugs                  #
#         other than his own.                                                  #
#                                                                              #
#      Please send copies of changes and bug-fixes to:                         #
#                                                                              #
#                             billq@technologist.com                           #
#                                                                              #
################################################################################
/bin/echo -n "			CHKUSER

chkusr prompts for a login i.d., and traverses their login directory,
searching for files that have not been modified in 120 days.

Whose login do you want to scan? [login id|?|q] "
read LOGIN
while [ "$LOGIN" = "?" ]
do
	echo "Logins available on this machine are:
	"
	grep `df|grep dev|awk '{print $6}'|sed '/usr/d'|sed '/^\/$/d'|sed '/var/d'` /etc/passwd|cut -f1 -d":"
	/bin/echo -n "Whose login do you want to scan? [login id|?|q] "
	read LOGIN
done
while [ "$LOGIN" != "q" ]
do
	/bin/echo -n "Where can I put the usage report? [ $LOGDIR/usage.$LOGIN ] "
	read REPT
	REPT=${REPT:-$LOGDIR/usage.$LOGIN}
	>$REPT 2>/dev/null
	if [ "$?" != "0" ]
	then
		echo "$0:ERROR:can not write in $REPT"
		sleep 2
		exit 1
	fi
	echo "Generating an old file report for $LOGIN, and storing in $REPT"
	USER=`logdir $LOGIN`
	echo "Mbytes	File name">$REPT
	find $USER -atime +120 -print | xargs du -s | sort -nr | head -30>>$REPT&
	/bin/echo -n "Whose login do you want to scan? [login id|q] "
	read LOGIN
done
