#!/bin/ksh
################################################################################
#                   @(#)Copyright (c) 1997 William R. Quayle                   #
#                             All Rights Reserved                              #
################################################################################
#                                                                              #
# This is free software.  It comes  with absolutely  NO WARRENTY  expressed or #
# implied.                                                                     #
#                            USE AT YOUR OWN RISK!                             #
#                                                                              #
# Permission is granted to use, modify, and distribute copies of this software #
# software  provided  the following conditions are met:                        #
#                                                                              #
#      1) that that the above copyright notice and this notice                 #
#         are preserved in all copies and that due credit be given             #
#         to the author.                                                       #
#                                                                              #
#      2) that any changes to this code are clearly commented                  #
#         as such so that the author does get blamed for bugs                  #
#         other than his own.                                                  #
#                                                                              #
#      Please send copies of changes and bug-fixes to:                         #
#                                                                              #
#                             billq@technologist.com                           #
#                                                                              #
################################################################################
echo "
#Here's a method that uses the count parameter of the dd command to
#locate the place to be patched. Assume:
#- the file "a.out" is to be patched
#- the patch consists of 10 bytes at byte offset 2048 of file a.out
#- the file "patch" is exactly 10 bytes long, and contains the patch
#- the file "a.new" will be created, to be renamed "a.out" after the
# patch is verified correct
#
"
#!/bin/sh
{
	dd ibs=1 obs=1k count=8807      # copy up to the patch point 
	dd bs=26 count=1 > /dev/null    # discard old stuff
	cat < patch                     # copy the patch
	dd bs=16k                       # copy the rest
} < saytime > s2
