#!/bin/bash
ARCHIVE=/home/bquayle
echo -n "Source dir? (relative path to $ARCHIVE)"
read DIR
SPARENT=$ARCHIVE/`dirname $DIR`
SDIR=`basename $DIR`
echo -n "Target dir? (relative path to $HOME)"
read TARGET
TPARENT=$HOME/`dirname $TARGET`
TDIR=`basename $TARGET`
cd $SPARENT
for i in `find $SDIR -type d`
do
  FLAG=0
  echo "Working in $i..."
  if [ ! -d "$TPARENT/$i" ]
  then
    echo $TPARENT/$i is missing. Relocating $i...
    mv $i $TARGET/
    if [ $? -ne 0 ]
    then
      echo Relocation of $i failed! Bailing out!
      exit 1
    fi
  else
    for j in `find $i/* -prune -type f`
    do
      if [ ! -f "$TPARENT/$j" ]
      then
        echo $TPARENT/$j is missing. Relocating $j....
        mv $j $TPARENT/$j
        if [ $? -ne 0 ]
        then
          echo Relocation of $j failed! Bailing out!
          exit 1
        fi
      else
        diff $j $TPARENT/$j >/dev/null 2>&1
        if [ $? -ne 0 ]
        then
          FLAG=1
        else
          rm -f $j
        fi
      fi
    done
  fi
  if [ "$FLAG" = "1" ]
  then
    echo "Files in archive differ from files in $TARGET.  Analizing..."
    for j in `find $i/* -prune -type f`
    do
      if [ ! -f "$TPARENT/$j" ]
      then
        echo $TPARENT/$j is missing.
      else
        diff $j $TPARENT/$j |more
        echo -n "Move, Destroy, or Ignore? [m|d|i] "
        read OPTION
        case $OPTION in
        m) mv $j $TPARENT/$j	;;
        d) rm $j	;;
        i) :	;;
        *) echo "Learn to type, ignoring."	;;
        esac
      fi
    done
  fi  
done
