#!/bin/ksh
################################################################################
#                   @(#)Copyright (c) 1997 William R. Quayle                   #
#                             All Rights Reserved                              #
################################################################################
#                                                                              #
# This is free software.  It comes  with absolutely  NO WARRENTY  expressed or #
# implied.                                                                     #
#                            USE AT YOUR OWN RISK!                             #
#                                                                              #
# Permission is granted to use, modify, and distribute copies of this software #
# software  provided  the following conditions are met:                        #
#                                                                              #
#      1) that that the above copyright notice and this notice                 #
#         are preserved in all copies and that due credit be given             #
#         to the author.                                                       #
#                                                                              #
#      2) that any changes to this code are clearly commented                  #
#         as such so that the author does get blamed for bugs                  #
#         other than his own.                                                  #
#                                                                              #
#      Please send copies of changes and bug-fixes to:                         #
#                                                                              #
#                             billq@technologist.com                           #
#                                                                              #
################################################################################
adb -k /vmunix /dev/mem << EOF
=n"Directory Name Cache Statistics Since Last Boot"
="-----------------------------------------------"
ncsize/D"Directory Name Cache Size"n
ncstats/D"cache hits"n
+/D"cache misses"n
+/D"number of enters into cache"n
+/D"number of enters tried when already cached"n
+/D"long names tried to enter"n
+/D"long names tried to look up"n
+/D"times LRU list empty"n
+/D"number of purges of cache"n
EOF
