#!/bin/ksh
################################################################################
#                   @(#)Copyright (c) 1997 William R. Quayle                   #
#                             All Rights Reserved                              #
################################################################################
#                                                                              #
# This is free software.  It comes  with absolutely  NO WARRENTY  expressed or #
# implied.                                                                     #
#                            USE AT YOUR OWN RISK!                             #
#                                                                              #
# Permission is granted to use, modify, and distribute copies of this software #
# software  provided  the following conditions are met:                        #
#                                                                              #
#      1) that that the above copyright notice and this notice                 #
#         are preserved in all copies and that due credit be given             #
#         to the author.                                                       #
#                                                                              #
#      2) that any changes to this code are clearly commented                  #
#         as such so that the author does get blamed for bugs                  #
#         other than his own.                                                  #
#                                                                              #
#      Please send copies of changes and bug-fixes to:                         #
#                                                                              #
#                             billq@technologist.com                           #
#                                                                              #
################################################################################
for param in tcp_close_wait_interval tcp_conn_req_max tcp_conn_grace_period \
tcp_cwnd_max tcp_debug tcp_smallest_nonpriv_port tcp_ip_abort_cinterval \
tcp_ip_abort_interval tcp_ip_notify_cinterval tcp_ip_notify_interval tcp_ip_ttl \
tcp_keepalive_interval tcp_maxpsz_multiplier tcp_mss_def tcp_mss_max \
tcp_mss_min tcp_naglim_def tcp_old_urp_interpretation tcp_rexmit_interval_initial \
tcp_rexmit_interval_max tcp_rexmit_interval_min tcp_wroff_xtra tcp_deferred_ack_interval \
tcp_snd_lowat_fraction tcp_sth_rcv_hiwat tcp_sth_rcv_lowat tcp_dupack_fast_retransmit \
tcp_ignore_path_mtu tcp_rwin_credit_pct tcp_rcv_push_wait tcp_smallest_anon_port \
tcp_largest_anon_port tcp_xmit_hiwat tcp_xmit_lowat tcp_recv_hiwat \
tcp_recv_hiwat_minmss tcp_fin_wait_2_flush_interval tcp_co_min tcp_max_buf \
tcp_zero_win_probesize tcp_strong_iss tcp_rtt_updates tcp_status \
tcp_bind_hash tcp_listen_hash tcp_conn_hash tcp_queue_hash
do
echo "ndd /dev/tcp $param"
ndd /dev/tcp $param
echo "Hit return to continue"
read go
done
