#!/bin/ksh
################################################################################
#                   @(#)Copyright (c) 1997 William R. Quayle                   #
#                             All Rights Reserved                              #
################################################################################
#                                                                              #
# This is free software.  It comes  with absolutely  NO WARRENTY  expressed or #
# implied.                                                                     #
#                            USE AT YOUR OWN RISK!                             #
#                                                                              #
# Permission is granted to use, modify, and distribute copies of this software #
# software  provided  the following conditions are met:                        #
#                                                                              #
#      1) that that the above copyright notice and this notice                 #
#         are preserved in all copies and that due credit be given             #
#         to the author.                                                       #
#                                                                              #
#      2) that any changes to this code are clearly commented                  #
#         as such so that the author does get blamed for bugs                  #
#         other than his own.                                                  #
#                                                                              #
#      Please send copies of changes and bug-fixes to:                         #
#                                                                              #
#                             billq@technologist.com                           #
#                                                                              #
################################################################################
for i in `cat $HOME/lib/goodsuns`
do
	DOM=`rsh $i /usr/bin/domainname`
	if [ "$DOM" = "switch.rockwell.com" ]
	then
		NET=`rsh $i "grep $i /etc/hosts"|cut -f3 -d. |head -1`
		case $NET in
		116)
			RTR=131.198.116.138
		;;
		*)
			RTR=131.198.${NET}.175
		;;
		esac
		rsh $i "echo $RTR > /etc/defaultrouter"
		echo $i is on $NET with $RTR for a router
		rsh $i "grep ifconfig /etc/rc.*"|grep '131\.198\.'
	fi
done
