#!/bin/ksh
################################################################################
#                   @(#)Copyright (c) 1997 William R. Quayle                   #
#                             All Rights Reserved                              #
################################################################################
#                                                                              #
# This is free software.  It comes  with absolutely  NO WARRENTY  expressed or #
# implied.                                                                     #
#                            USE AT YOUR OWN RISK!                             #
#                                                                              #
# Permission is granted to use, modify, and distribute copies of this software #
# software  provided  the following conditions are met:                        #
#                                                                              #
#      1) that that the above copyright notice and this notice                 #
#         are preserved in all copies and that due credit be given             #
#         to the author.                                                       #
#                                                                              #
#      2) that any changes to this code are clearly commented                  #
#         as such so that the author does get blamed for bugs                  #
#         other than his own.                                                  #
#                                                                              #
#      Please send copies of changes and bug-fixes to:                         #
#                                                                              #
#                             billq@technologist.com                           #
#                                                                              #
################################################################################
#######################################################################
#		fmond 
#    		 
#		Date: 27 Nov 16:11 
#			 
#		Author : dyt (David Tran) 
#			 
#		Monitors the .plan and .project pipes
#			 
#######################################################################

#trap '
	# ignore subsequent signals
#	trap "" 0 1 2
	# No point having the pipes if fmond is not running
	rm -f $HOME/.project $HOME/.plan
#' 0 1 2

# create the pipe files
rm -f $HOME/.plan $HOME/.project
/etc/mknod $HOME/.plan p || {
	echo "Can not create .plan"
	exit 1
}
/etc/mknod $HOME/.project p || {
	echo "Can not create .project"
	exit 1
}

i=0
ME=`whoami | awk '{ print $1 }'`

while :
do
	# write to the pipe, this only returns if a process attempts
	# to read from the pipe
	echo ' ' > $HOME/.project

	# The same process will try to read from the .plan file
	# Some optimisation can be done here on systems with slow ps
	if [ $i -eq 0 ]; then

		# uncomment the appropriate line for the ps of your
		# system
		U=`ps -au | grep "finger"`
       #        U=`ps -ef | grep "finger"`

		# get the id of the culprit from the ps entry
		U=`echo "$U" | awk '{ if ($(NF - 1) != "grep" ) print $1 }'`
		# now get his name from the passwd file
		NAME=`fgrep "$U" /etc/passwd | awk -F: '{ print $5 }'`
		# add the personal touch, only use first name
		FIRSTNAME=`echo $NAME | awk '{ print $1 }'`
 	fi
	
	# This is the message he will read on his screen for the contents
	# of the .plan file, that ought to scare him !!
	echo "Hello $FIRSTNAME, please stop fingering me, it tickles !!" > $HOME/.plan

# YIKES! I sure as hell don't want this stupid message blurped out on
# all my windows!  Let's just send it to the console...
	# Now find out where I am logged in, could be a few if under X ...
#	PORTS=`who | fgrep $ME | awk ' { print $2 }' | sort -u` 

	# number of ttys to output message to
#	NPORTS=`echo "$PORTS" | wc -w`
	
	# the pipes are read from as many times as the number of
	# times I am logged in. So only print the messages once i.e.
	# when $i is 0, $i is incremented on each iteration of the loop

#	if [ $i -eq 0 ]; then
#		for PORT in $PORTS
#		do
			# I will get a message like this printed to all
			# the tty windows I am logged in, telling me
			# who fingered me
#			echo "$NAME" fingered you at `date` > /dev/"$PORT"
			echo "$NAME" fingered you at `date` > /dev/console
#		done
#	fi

	i=`expr $i + 1`
#	i=`expr $i % $NPORTS`
done
