#!/bin/ksh
################################################################################
#                   @(#)Copyright (c) 1992 William R. Quayle                   #
#                             All Rights Reserved                              #
################################################################################
#                                                                              #
# This is free software.  It comes  with absolutely  NO WARRENTY  expressed or #
# implied.                                                                     #
#                            USE AT YOUR OWN RISK!                             #
#                                                                              #
# Permission is granted to use, modify, and distribute copies of this software #
# software  provided  the following conditions are met:                        #
#                                                                              #
#      1) that that the above copyright notice and this notice                 #
#         are preserved in all copies and that due credit be given             #
#         to the author.                                                       #
#                                                                              #
#      2) that any changes to this code are clearly commented                  #
#         as such so that the author does get blamed for bugs                  #
#         other than his own.                                                  #
#                                                                              #
#      Please send copies of changes and bug-fixes to:                         #
#                                                                              #
#                             billq@technologist.com                           #
#                                                                              #
################################################################################
#
ACCFILE="$LOGDIR/usage/connecttime.`date +%j`"
if [ ! -n $SUNS ]
then
	echo "Sorry, you have to have an environmental variable set called SUNS,"
	echo "that is the list of those machines you're interested in."
	exit 1
fi
for i in $SUNS
do
	echo "
Usage summary for $i on `date`
">>$ACCFILE
	if [ "$i" = "$UNAME" ]; then
		/usr/etc/ac -p|/usr/5bin/sort -bnr +1.0>>$ACCFILE
		cat /dev/null>/usr/adm/wtmp
	else
		rsh $i /usr/etc/ac -p|/usr/5bin/sort -bnr +1.0>>$ACCFILE
		rsh $i "cat /dev/null>/usr/adm/wtmp"
	fi
done
cat $ACCFILE|postprint -n2 -l100|postreverse>/tmp/usg.$$
rm -f $ACCFILE
lpr /tmp/usg.$$
rm -f /tmp/usg.$$
