#!/bin/ksh
################################################################################
#                   @(#)Copyright (c) 1997 William R. Quayle                   #
#                             All Rights Reserved                              #
################################################################################
#                                                                              #
# This is free software.  It comes  with absolutely  NO WARRENTY  expressed or #
# implied.                                                                     #
#                            USE AT YOUR OWN RISK!                             #
#                                                                              #
# Permission is granted to use, modify, and distribute copies of this software #
# software  provided  the following conditions are met:                        #
#                                                                              #
#      1) that that the above copyright notice and this notice                 #
#         are preserved in all copies and that due credit be given             #
#         to the author.                                                       #
#                                                                              #
#      2) that any changes to this code are clearly commented                  #
#         as such so that the author does get blamed for bugs                  #
#         other than his own.                                                  #
#                                                                              #
#      Please send copies of changes and bug-fixes to:                         #
#                                                                              #
#                             billq@technologist.com                           #
#                                                                              #
################################################################################
cd $HOME
ls /usr/local > tools
for i in `cat tools`
do
  if [ -d "/usr/local/${i}/bin" ]
  then
    echo "export ${i};	${i}=${i}/bin" >> TOOLPLACES
    NEWPATH="$NEWPATH:${i}/bin"
  fi
done
echo -n "Your PATH can be: 

$NEWPATH

You should edit your .profile and source in the file
called TOOLPLACES.

Hit RETURN:"
read junk
vi .profile
