#!/bin/ksh
# hostmon - monitor hosts and report down
SLEEPTIME=${SLEEPTIME:-600}
SOUNDIR=/adm/lib/sounds
PATH=$PATH:/usr/local/bin
SERVERS="hercules raven yooper trooper chaos tbsun2 bootes cetus zeus thor orion camelot tbsun rib zod"

FLASH () {
if [ -c /dev/audio ]
then
	play -v 100 ${SOUNDIR}/alert.au
	play -v 100 ${SOUNDIR}/${SERVER}.au
	play -v 100 ${SOUNDIR}/is_down.au
else
	echo 
fi
}

while true
do
	clear
	echo "HOST                                    STAUS"
	echo "------------------------------------------------"

	for SERVER in $SERVERS
	do
		spray -c 1 -l 1 -d 1 $SERVER >/dev/null 2>&1
		if [ $? -ne 0 ]
		then
			FLASH
			echo "$SERVER                                 DOWN"
			echo "------------------------------------------------"
		else
			echo "$SERVER                                  UP"
			echo "------------------------------------------------"
		fi
	done
	sleep $SLEEPTIME
done
