#!/bin/ksh
################################################################################
#                   @(#)Copyright (c) 1997 William R. Quayle                   #
#                             All Rights Reserved                              #
################################################################################
#                                                                              #
# This is free software.  It comes  with absolutely  NO WARRENTY  expressed or #
# implied.                                                                     #
#                            USE AT YOUR OWN RISK!                             #
#                                                                              #
# Permission is granted to use, modify, and distribute copies of this software #
# software  provided  the following conditions are met:                        #
#                                                                              #
#      1) that that the above copyright notice and this notice                 #
#         are preserved in all copies and that due credit be given             #
#         to the author.                                                       #
#                                                                              #
#      2) that any changes to this code are clearly commented                  #
#         as such so that the author does get blamed for bugs                  #
#         other than his own.                                                  #
#                                                                              #
#      Please send copies of changes and bug-fixes to:                         #
#                                                                              #
#                             billq@technologist.com                           #
#                                                                              #
################################################################################
if [ "$1" = "" ]
then
	/bin/echo -n "Give me a name of a process to kill ->"
	read NAME
else
	NAME=$1
	echo "Setting the name of the doomed process to $NAME"
fi
/bin/echo -n "Please choose a level...

		1  = sighup, reinit process
		9  = sure kill, but may leave children
		15 = make sure children are dead too

		Level of kill? -> [15] "
read LEVEL
case $LEVEL in
1)	LEVEL=-1		;;
9)	LEVEL=-9		;;
*)	LEVEL=""	;;
esac
ps -awwux |grep -v "killbyname $NAME"|grep $NAME|sed '/grep/d'
/bin/echo -n "O.K. to kill all of these? [Y|n] ->"
read GOFORIT
case $GOFORIT
in
y*|Y*|"")
	for i in `ps -aux|grep -v "killbyname $NAME"|grep $NAME |sed 's/  */:/g'|sed '/grep/d'|cut -f2 -d":"`
	do
		kill $LEVEL $i
	done
	;;
*)
	echo "No kills done"
	exit 1
	;;
esac
