#!/bin/ksh
################################################################################
#                   @(#)Copyright (c) 1997 William R. Quayle                   #
#                             All Rights Reserved                              #
################################################################################
#                                                                              #
# This is free software.  It comes  with absolutely  NO WARRENTY  expressed or #
# implied.                                                                     #
#                            USE AT YOUR OWN RISK!                             #
#                                                                              #
# Permission is granted to use, modify, and distribute copies of this software #
# software  provided  the following conditions are met:                        #
#                                                                              #
#      1) that that the above copyright notice and this notice                 #
#         are preserved in all copies and that due credit be given             #
#         to the author.                                                       #
#                                                                              #
#      2) that any changes to this code are clearly commented                  #
#         as such so that the author does get blamed for bugs                  #
#         other than his own.                                                  #
#                                                                              #
#      Please send copies of changes and bug-fixes to:                         #
#                                                                              #
#                             billq@technologist.com                           #
#                                                                              #
################################################################################
shelltool -Wt "-adobe-courier-bold-r-normal--14-140-75-75-m-90-iso8859-1" -Wp 0 0 -Ws 656 797 -WP 942 0 -Wl "LOGBK" -WL "logbk"
LOGFILE=/usr/add-on/adm/log/logbk
while true
do
/bin/echo -n "Re: "
	read RE
	echo "Re: $RE">>$LOGFILE
	clear
/bin/echo -n "Status: "
	read STAT
	echo "Status: $STAT">>$LOGFILE
	clear
/bin/echo -n "Time: "
	read TIME
	echo "Time: $TIME">>$LOGFILE
	clear
/bin/echo -n "Spew: "
	read SPEW
	echo "Spew: $SPEW">>$LOGFILE
	clear
done
