#!/bin/ksh
################################################################################
#                   @(#)Copyright (c) 1997 William R. Quayle                   #
#                             All Rights Reserved                              #
################################################################################
#                                                                              #
# This is free software.  It comes  with absolutely  NO WARRENTY  expressed or #
# implied.                                                                     #
#                            USE AT YOUR OWN RISK!                             #
#                                                                              #
# Permission is granted to use, modify, and distribute copies of this software #
# software  provided  the following conditions are met:                        #
#                                                                              #
#      1) that that the above copyright notice and this notice                 #
#         are preserved in all copies and that due credit be given             #
#         to the author.                                                       #
#                                                                              #
#      2) that any changes to this code are clearly commented                  #
#         as such so that the author does get blamed for bugs                  #
#         other than his own.                                                  #
#                                                                              #
#      Please send copies of changes and bug-fixes to:                         #
#                                                                              #
#                             billq@technologist.com                           #
#                                                                              #
################################################################################
cd /usr/lib/uucp
ls -FC
/bin/echo -n "Where's the NEW stuff? [NEW] "
read THERE
THERE=${THERE:-NEW}
if [ -d $THERE ]
then
	cd $THERE
else
	echo "Can't find $THERE"
	exit 1
fi
ls -FC *.cpio*
/bin/echo -n "Are the cpio files unpacked? [y|N] "
read CPIO
case $CPIO in
Y*|y*)
	echo "Assuming cpio files unpacked."
	;;
*)
	MONTH="`date +%h|tr [a-z] [A-Z]`"
	/bin/echo -n "What month? [$MONTH] "
	read UMONTH
	MONTH=${UMONTH:-$MONTH}
	/bin/echo -n "Unpacking cpio files..."
	for i in 1 2 3 4 5 6
	do
		if [ -f ${MONTH}.cpio${i} ]
		then
			cpio -idum < ${MONTH}.cpio${i}
		fi
	done
	echo "done."
	;;
esac
/bin/echo -n "O.K. to do the make? [Y|n] "
read MAKE
case $MAKE in
n*|N*)
	echo "Nothing to do!"
	exit
	;;
*)
	make DIAL=outchicago GATE=IH SYS=DKH,TCP,TLI1,TLI2,DKT uucp
	;;
esac
/bin/echo -n "O.K. to do the make install? [Y|n] "
read MAKE
case $MAKE in
N*|n*)
	echo "Nothing to do!"
	exit
	;;
*)
	make LOCAL=QFT install
	;;
esac
