#!/bin/ksh
################################################################################
#                   @(#)Copyright (c) 1997 William R. Quayle                   #
#                             All Rights Reserved                              #
################################################################################
#                                                                              #
# This is free software.  It comes  with absolutely  NO WARRENTY  expressed or #
# implied.                                                                     #
#                            USE AT YOUR OWN RISK!                             #
#                                                                              #
# Permission is granted to use, modify, and distribute copies of this software #
# software  provided  the following conditions are met:                        #
#                                                                              #
#      1) that that the above copyright notice and this notice                 #
#         are preserved in all copies and that due credit be given             #
#         to the author.                                                       #
#                                                                              #
#      2) that any changes to this code are clearly commented                  #
#         as such so that the author does get blamed for bugs                  #
#         other than his own.                                                  #
#                                                                              #
#      Please send copies of changes and bug-fixes to:                         #
#                                                                              #
#                             billq@technologist.com                           #
#                                                                              #
################################################################################
/bin/echo -n "Netgroup builder going to work..."
cd /usr/add-on/adm/etc
>netgroup
>nogroup
for HOST in ih4ehz ih4ehw ih4epd ih4elab ih4sh
do
  /bin/echo -n "{${HOST},,)" > netgroup.${HOST}
  for i in a b c d e f g h i j k l m n o p q r s t u v w x y z
  do
    ping ${HOST}${i} 2 > /dev/null 2>&1
    if [ $? = 0 ]
    then
      /bin/echo -n "(${HOST}${i},,) " >> netgroup.${HOST}
    else
      /bin/echo -n "(${HOST}${i},,) " >> nogroup
    fi
  done
  for n in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20
  do
    ping ${HOST}${n} 2 > /dev/null 2>&1
    if [ $? = 0 ]
    then
      /bin/echo -n "(${HOST}${n},,) " >> netgroup.${HOST}
    else
      /bin/echo -n "(${HOST}${n},,) " >> nogroup
    fi
  done
  echo "" >> netgroup.${HOST}
  cat netgroup.${HOST} netgroup >> netgroup.new 2>/dev/null
  mv netgroup.new netgroup
done
echo "done"
vi netgroup
