#!/bin/ksh
################################################################################
#                   @(#)Copyright (c) 1997 William R. Quayle                   #
#                             All Rights Reserved                              #
################################################################################
#                                                                              #
# This is free software.  It comes  with absolutely  NO WARRENTY  expressed or #
# implied.                                                                     #
#                            USE AT YOUR OWN RISK!                             #
#                                                                              #
# Permission is granted to use, modify, and distribute copies of this software #
# software  provided  the following conditions are met:                        #
#                                                                              #
#      1) that that the above copyright notice and this notice                 #
#         are preserved in all copies and that due credit be given             #
#         to the author.                                                       #
#                                                                              #
#      2) that any changes to this code are clearly commented                  #
#         as such so that the author does get blamed for bugs                  #
#         other than his own.                                                  #
#                                                                              #
#      Please send copies of changes and bug-fixes to:                         #
#                                                                              #
#                             billq@technologist.com                           #
#                                                                              #
################################################################################
ln -s /home/voodoo /users01
ln -s /home/raven /users12
ln -s /home/zod /users13
ln -s /home/zod1 /users13b
ln -s /home/corsair /users18
ln -s /home/wweasel /users20
ln -s /home/o1 /usr1
ln -s /home/o5 /usr10
ln -s /home/camelot /usr2
ln -s /home/o2 /usr3
ln -s /home/t1 /usr4
ln -s /home/o3 /usr5
ln -s /home/o4 /usr6
ln -s /home/t2 /usr7
ln -s /home/z1 /usr8
ln -s /home/z2 /usr9
