#!/bin/ksh
# @(#)mvheir/diskswap     0.1 (William R. Quayle) 05/27/93
################################################################################
#                   @(#)Copyright (c) 1993 William R. Quayle                   #
#                             All Rights Reserved                              #
################################################################################
#                                                                              #
# This is free software.  It comes  with absolutely  NO WARRENTY  expressed or #
# implied.                                                                     #
#                            USE AT YOUR OWN RISK!                             #
#                                                                              #
# Permission is granted to use, modify, and distribute copies of this software #
# software  provided  the following conditions are met:                        #
#                                                                              #
#      1) that that the above copyright notice and this notice                 #
#         are preserved in all copies and that due credit be given             #
#         to the author.                                                       #
#                                                                              #
#      2) that any changes to this code are clearly commented                  #
#         as such so that the author does get blamed for bugs                  #
#         other than his own.                                                  #
#                                                                              #
#      Please send copies of changes and bug-fixes to:                         #
#                                                                              #
#                          quayle@switch.rockwell.com                          #
#                                                                              #
################################################################################
################################################################################
stty intr ^C
if [ $# -lt 1 ]
then
	echo "USAGE:$0 source targetdir"
	case $0 in
	mvheir)
		echo "source is the full path to the heirarchy you want copied."
		echo "targetdir is the full path to the top of the new heirarchy."
	;;
	diskswap)
		echo "source is the raw device to dump."
		echo "targetdir is the full path to the top of the new partition."
	;;
	esac
	exit 1
fi
CMD=`basename $0`
SRC=$1
TGT=$2
if [ ! -d $SRC ]
then
	echo "$SRC aint there!"
	exit 1
fi
if [ ! -d $TGT ]
then
	echo "making $TGT"
	mkdir $TGT >/dev/null 2>&1
	if [ $? -ne 0 ]
	then
		echo "Can't make $TGT"
		exit 1
	fi
fi
case $CMD in
mvheir)
	cd $SRC
	#
	# I like tar, but it just doesn't handle the long paths...
	#tar -cef - . | (cd $TGT; tar -xlvfBp -)
	/bin/echo -n  "Ready to copy $SRC to $TGT, hit return to fire,
or ^C to bail out..."
	read go
	find . -depth -print | cpio -pvdlm $TGT
;;
diskswap)
	/etc/dump 0f - $SRC | (cd $TGT; /etc/restore xvf -)
;;
esac
echo "now it's up to you to get rid of the old stuff..."

