#!/bin/ksh
MAN=$1
if [ "$MAN" = "" ]
then
  echo "USAGE:mycatman mandir"
  exit 1
fi
if [ -d ${MAN} ]
then
  cd ${MAN}
else
  echo "Can't find ${MAN}!"
  exit 1
fi
for SECTION in 1 2 3 4 5 6 7 8 l n
do
  if [ -d man${SECTION} ]
  then
    if [ ! -d cat${SECTION} ]
    then
      mkdir cat${SECTION} > /dev/null 2>&1
      if [ $? -ne 0 ]
      then
        echo "Can't make cat${SECTION}!"
        exit 1
      fi
    fi
    for PAGE in `ls man${SECTION}`
    do
      echo "Ready to format man${SECTION}/${PAGE} into cat${SECTION}/${PAGE}"
      /usr/5bin/tbl man${SECTION}/${PAGE} | /usr/5bin/nroff -T37 -man |/usr/5bin/col > cat${SECTION}/${PAGE}
    done
  else
    echo "Can't find man${SECTION}"
  fi
done
