#!/bin/ksh
################################################################################
#                   @(#)Copyright (c) 1997 William R. Quayle                   #
#                             All Rights Reserved                              #
################################################################################
#                                                                              #
# This is free software.  It comes  with absolutely  NO WARRENTY  expressed or #
# implied.                                                                     #
#                            USE AT YOUR OWN RISK!                             #
#                                                                              #
# Permission is granted to use, modify, and distribute copies of this software #
# software  provided  the following conditions are met:                        #
#                                                                              #
#      1) that that the above copyright notice and this notice                 #
#         are preserved in all copies and that due credit be given             #
#         to the author.                                                       #
#                                                                              #
#      2) that any changes to this code are clearly commented                  #
#         as such so that the author does get blamed for bugs                  #
#         other than his own.                                                  #
#                                                                              #
#      Please send copies of changes and bug-fixes to:                         #
#                                                                              #
#                             billq@technologist.com                           #
#                                                                              #
################################################################################
shelltool -Wp 1 1801 -Ws 560 270 -WP 1020 1720 -Wt -misc-fixed-medium-r-normal--10-100-75-75-c-60-iso8859-1 -Wl "NFSWATCH on ie0" -WL nfs_ie0 
shelltool -Wp 1 2101 -Ws 560 270 -WP 1020 2220 -Wt -misc-fixed-medium-r-normal--10-100-75-75-c-60-iso8859-1 -Wl "NFSWATCH on ne0" -WL nfs_ne0 
shelltool -Wp 1 2402 -Ws 560 270 -WP 1020 2720 -Wt -misc-fixed-medium-r-normal--10-100-75-75-c-60-iso8859-1 -Wl "NFSWATCH on ne1" -WL nfs_ne1 
