#!/bin/ksh
# catch swapping and report
#
vmstat -S 5 | awk '
/r/	{ next }
	{ 
	  if ($5 > 100000) {next}
	  if ($3 > 0) {printf ("blocked procs:\t%12s\n", $3) 
			system (date) }
	  if ($7 > 0) {printf ("swapped out:\t%12s\n", $7) 
			system (date) }
	  if ($9 > 0) {printf ("paged out:\t%12s\n", $9) 
			system (date) }
	  if ($11 > 0) {printf ("desperation swapping:\t%12s\n", $11) 
			system (date) }
	}'
