#!/bin/ksh
################################################################################
#                   @(#)Copyright (c) 1997 William R. Quayle                   #
#                             All Rights Reserved                              #
################################################################################
#                                                                              #
# This is free software.  It comes  with absolutely  NO WARRENTY  expressed or #
# implied.                                                                     #
#                            USE AT YOUR OWN RISK!                             #
#                                                                              #
# Permission is granted to use, modify, and distribute copies of this software #
# software  provided  the following conditions are met:                        #
#                                                                              #
#      1) that that the above copyright notice and this notice                 #
#         are preserved in all copies and that due credit be given             #
#         to the author.                                                       #
#                                                                              #
#      2) that any changes to this code are clearly commented                  #
#         as such so that the author does get blamed for bugs                  #
#         other than his own.                                                  #
#                                                                              #
#      Please send copies of changes and bug-fixes to:                         #
#                                                                              #
#                             billq@technologist.com                           #
#                                                                              #
################################################################################
echo "This utility will scan a filesystem for empty directories, allowing
selective interactive deletion."
/bin/echo -n "Please enter a root directory path to start scanning from.

	[.] -> "
read RROOT
cd $RROOT
for i in `find . -type d -print`
do
	cd $i
	if [ "`echo .*`" = ". .." ] && [ `echo *` = "*" ] 2>/dev/null
	then
		echo "No files in $i"
		cd $RROOT
		/bin/echo -n "Remove $i ? [Y|n] -> "
		read KILLIT
		case $KILLIT in
		""|Y*|y*)
			rmdir $i
		;;
		*)
			echo "Preserved $i"
		;;
		esac
	fi
	cd $RROOT
done
