#!/bin/ksh
################################################################################
#                   @(#)Copyright (c) 1997 William R. Quayle                   #
#                             All Rights Reserved                              #
################################################################################
#                                                                              #
# This is free software.  It comes  with absolutely  NO WARRENTY  expressed or #
# implied.                                                                     #
#                            USE AT YOUR OWN RISK!                             #
#                                                                              #
# Permission is granted to use, modify, and distribute copies of this software #
# software  provided  the following conditions are met:                        #
#                                                                              #
#      1) that that the above copyright notice and this notice                 #
#         are preserved in all copies and that due credit be given             #
#         to the author.                                                       #
#                                                                              #
#      2) that any changes to this code are clearly commented                  #
#         as such so that the author does get blamed for bugs                  #
#         other than his own.                                                  #
#                                                                              #
#      Please send copies of changes and bug-fixes to:                         #
#                                                                              #
#                             billq@technologist.com                           #
#                                                                              #
################################################################################
trap "" 1 3

if [ "$1" = "" ]
then
    echo "usage: peek machine"
    exit
fi

rsh $1 who >/dev/null 2>&1
if [ "$?" != "0" ]
then
	echo "OOPS!!! You gotta have rsh access to $1."
	sleep 1
	echo "Life's a bummer."
	sleep 2
	exit 1
fi

if [ "$WINDOW_ME" = "" ]
then
	echo "Sorry, you've got to be in sunview for this to work..."
	exit 1
fi
echo "Patience, please..."
echo "Bang on return when you want a refresh"
rsh $1 screendump | screenload 2>/dev/null
if [ "$?" != "0" ]
then
	echo "OOPS!!! $1 must not match your display type, eh?<-|
						(yooperscript)--|
	Hold on, while I do it again."
	rsh $1 screendump | rasfilter8to1 | screenload
fi
read GO
refresh
