#!/bin/ksh
cd ~bquayle/log
ls -FC
echo "Hey, pick a directory: \c"
read subsys
[[ -d "$subsys" ]] && {
cd $subsys
for i in `ls *PM.log`
do
  I=`echo $i|sed 's/_PM.log//'`
  for j in `cat ${i}|awk '{print $1}'|sort -u|grep "^[0-9]"`
  do
    J=`echo ${j}|sed 's/\///g'`
    grep "^${j}" ${i}|awk '{print $2,$4}'|sed 's/cpu=//'|sed 's/:/./' > ${I}.${J}
    gnuplot "${I}.${J}"
  done
done
}
