#!/bin/ksh
################################################################################
#                   @(#)Copyright (c) 1997 William R. Quayle                   #
#                             All Rights Reserved                              #
################################################################################
#                                                                              #
# This is free software.  It comes  with absolutely  NO WARRENTY  expressed or #
# implied.                                                                     #
#                            USE AT YOUR OWN RISK!                             #
#                                                                              #
# Permission is granted to use, modify, and distribute copies of this software #
# software  provided  the following conditions are met:                        #
#                                                                              #
#      1) that that the above copyright notice and this notice                 #
#         are preserved in all copies and that due credit be given             #
#         to the author.                                                       #
#                                                                              #
#      2) that any changes to this code are clearly commented                  #
#         as such so that the author does get blamed for bugs                  #
#         other than his own.                                                  #
#                                                                              #
#      Please send copies of changes and bug-fixes to:                         #
#                                                                              #
#                             billq@technologist.com                           #
#                                                                              #
################################################################################
#!/bin/sh
MAN=$1
if [ "$MAN" = "" ]
then
  echo "USAGE:printman manpage"
  exit 1
fi
if [ "x$ENSCRIPT" = "x" ]
then
  ENSCRIPT=lpr
else
  ENSCRIPT="enscript -G -fHelvetica12"
fi
/usr/bin/tbl $MAN | /usr/bin/nroff -T37 -man |/usr/bin/col > /tmp/cat$MAN
if [ -r /tmp/cat$MAN ]
then
  $ENSCRIPT /tmp/cat$MAN
else
  echo "Can't find man${SECTION}"
fi
