#!/bin/ksh
################################################################################
#                   @(#)Copyright (c) 1997 William R. Quayle                   #
#                             All Rights Reserved                              #
################################################################################
#                                                                              #
# This is free software.  It comes  with absolutely  NO WARRENTY  expressed or #
# implied.                                                                     #
#                            USE AT YOUR OWN RISK!                             #
#                                                                              #
# Permission is granted to use, modify, and distribute copies of this software #
# software  provided  the following conditions are met:                        #
#                                                                              #
#      1) that that the above copyright notice and this notice                 #
#         are preserved in all copies and that due credit be given             #
#         to the author.                                                       #
#                                                                              #
#      2) that any changes to this code are clearly commented                  #
#         as such so that the author does get blamed for bugs                  #
#         other than his own.                                                  #
#                                                                              #
#      Please send copies of changes and bug-fixes to:                         #
#                                                                              #
#                             billq@technologist.com                           #
#                                                                              #
################################################################################
for i in $SUNS
do
	case $i in
	ih4sh|ih4elab|ih4ehz|ih4epd|ih4ehw|ih4ehwa|ih4ehzc)
		echo "skipping server"
		;;
	*)
	ping $i 2
	if [ $? = 0 ]
	then
		#if [ `rsh $i file /bin/sh|sed 's/	//g'|sed 's/ /:/g'|cut -f2 -d:` = "sparc" ]
		#then
			#echo getting fstab
			#rcp $i:/etc/fstab /tmp/fstab.$i
			#echo fixing fstab
			#cat /tmp/fstab.$i|sed 's/u2/b2/g'>/tmp/fstab
			#echo putting fstab back
			#rcp /tmp/fstab $i:/etc/fstab
			#echo cleaning up
			#rm /tmp/fstab.*
			#echo going to $i
			#rlogin $i
			rsh $i shutdown -r +5 &
			sleep 5
		#fi
	fi
		;;
	esac
done
