#!/bin/ksh
################################################################################
#                   @(#)Copyright (c) 1997 William R. Quayle                   #
#                             All Rights Reserved                              #
################################################################################
#                                                                              #
# This is free software.  It comes  with absolutely  NO WARRENTY  expressed or #
# implied.                                                                     #
#                            USE AT YOUR OWN RISK!                             #
#                                                                              #
# Permission is granted to use, modify, and distribute copies of this software #
# software  provided  the following conditions are met:                        #
#                                                                              #
#      1) that that the above copyright notice and this notice                 #
#         are preserved in all copies and that due credit be given             #
#         to the author.                                                       #
#                                                                              #
#      2) that any changes to this code are clearly commented                  #
#         as such so that the author does get blamed for bugs                  #
#         other than his own.                                                  #
#                                                                              #
#      Please send copies of changes and bug-fixes to:                         #
#                                                                              #
#                             billq@technologist.com                           #
#                                                                              #
################################################################################
#	RMTFS: remount all disks on all clients and servers.
#
ERR="ERROR:$0:"
HOSTNAME=`/bin/hostname`
OPER=`/usr/ucb/whoami`
if [ "$OPER" != "root" ]
then
	echo $ERR"Not logged in as root"
	sleep 2
	exit 1
fi

for i in $SUNS
do
	echo "mounting FS on ${i}:"
	rsh $i /etc/mount -at nfs
done

echo "mounting FS on ${HOSTNAME}:"
/etc/mount -at nfs

echo "Mounts done."
