#!/bin/ksh
################################################################################
#                   @(#)Copyright (c) 1997 William R. Quayle                   #
#                             All Rights Reserved                              #
################################################################################
#                                                                              #
# This is free software.  It comes  with absolutely  NO WARRENTY  expressed or #
# implied.                                                                     #
#                            USE AT YOUR OWN RISK!                             #
#                                                                              #
# Permission is granted to use, modify, and distribute copies of this software #
# software  provided  the following conditions are met:                        #
#                                                                              #
#      1) that that the above copyright notice and this notice                 #
#         are preserved in all copies and that due credit be given             #
#         to the author.                                                       #
#                                                                              #
#      2) that any changes to this code are clearly commented                  #
#         as such so that the author does get blamed for bugs                  #
#         other than his own.                                                  #
#                                                                              #
#      Please send copies of changes and bug-fixes to:                         #
#                                                                              #
#                             billq@technologist.com                           #
#                                                                              #
################################################################################
shelltool  -Wp    0  37 -Ws 657 573 -WP  964 144 -c -Wl <<HERCULES>> -WL herc sh -c "exec rsh hercules vmstat -S 5" &
shelltool  -Wp    0  74 -Ws 656 573 -WP  964 204 -c -Wl <<CHAOS>> -WL chaos sh -c "exec rsh chaos vmstat -S 5" &
shelltool  -Wp    0 109 -Ws 657 573 -WP  964 264 -c -Wl <<TROOPER>> -WL trooper sh -c "exec rsh trooper vmstat -S 5" &
shelltool  -Wp    0 143 -Ws 657 573 -WP  964 324 -c -Wl <<RAVEN>> -WL raven sh -c "exec rsh raven vmstat -S 5" &
shelltool  -Wp    0 143 -Ws 657 573 -WP  964 324 -c -Wl <<SOLARIS2>> -WL solaris2 sh -c "exec rsh solaris2 vmstat -S 5" &
shelltool  -Wp    0 143 -Ws 657 573 -WP  964 324 -c -Wl <<YOOPER>> -WL yooper sh -c "exec vmstat -S 5" &
