#!/bin/ksh
################################################################################
#                   @(#)Copyright (c) 1997 William R. Quayle                   #
#                             All Rights Reserved                              #
################################################################################
#                                                                              #
# This is free software.  It comes  with absolutely  NO WARRENTY  expressed or #
# implied.                                                                     #
#                            USE AT YOUR OWN RISK!                             #
#                                                                              #
# Permission is granted to use, modify, and distribute copies of this software #
# software  provided  the following conditions are met:                        #
#                                                                              #
#      1) that that the above copyright notice and this notice                 #
#         are preserved in all copies and that due credit be given             #
#         to the author.                                                       #
#                                                                              #
#      2) that any changes to this code are clearly commented                  #
#         as such so that the author does get blamed for bugs                  #
#         other than his own.                                                  #
#                                                                              #
#      Please send copies of changes and bug-fixes to:                         #
#                                                                              #
#                             billq@technologist.com                           #
#                                                                              #
################################################################################
toolwait shelltool -Wp 1 1 -Ws 570 870 -WP 1 1 -Wi -Wt -misc-fixed-bold-r-normal--13-120-75-75-c-70-iso8859-1 -Wl LEFT -WL left &
toolwait shelltool -Wp 584 1 -Ws 570 870 -WP 84 1 -Wi -Wt -misc-fixed-bold-r-normal--13-120-75-75-c-70-iso8859-1 -Wl RIGHT -WL right &
