#!/bin/ksh
################################################################################
#                   @(#)Copyright (c) 1997 William R. Quayle                   #
#                             All Rights Reserved                              #
################################################################################
#                                                                              #
# This is free software.  It comes  with absolutely  NO WARRENTY  expressed or #
# implied.                                                                     #
#                            USE AT YOUR OWN RISK!                             #
#                                                                              #
# Permission is granted to use, modify, and distribute copies of this software #
# software  provided  the following conditions are met:                        #
#                                                                              #
#      1) that that the above copyright notice and this notice                 #
#         are preserved in all copies and that due credit be given             #
#         to the author.                                                       #
#                                                                              #
#      2) that any changes to this code are clearly commented                  #
#         as such so that the author does get blamed for bugs                  #
#         other than his own.                                                  #
#                                                                              #
#      Please send copies of changes and bug-fixes to:                         #
#                                                                              #
#                             billq@technologist.com                           #
#                                                                              #
################################################################################
xterm -iconic -j -rw -sl 1000 -sf -tm 'intr ^c erase ^? kill ^u' -geometry 80X50 -n trooper -e rlogin trooper -l qroot &
xterm -iconic -j -rw -sl 1000 -sf -tm 'intr ^c erase ^? kill ^u' -geometry 80X50 -n london -e rlogin london -l qroot &
xterm -iconic -j -rw -sl 1000 -sf -tm 'intr ^c erase ^? kill ^u' -geometry 80X50 -n hercules -e rlogin hercules -l qroot &
xterm -iconic -j -rw -sl 1000 -sf -tm 'intr ^c erase ^H kill ^u' -n ksh -geometry 80X50+0+80 -xrm '*iconGeometry: 80x80+0+0' &
xterm -iconic -j -rw -sl 1000 -sf -tm 'intr ^c erase ^H kill ^u' -n ksh -geometry 80X50+80+80 -xrm '*iconGeometry: 80x80+0+0' -e /bin/su - qroot &
xterm -iconic -j -rw -sl 1000 -sf -tm 'intr ^c erase ^H kill ^u' -n ksh -geometry 80X50+0+80 -xrm '*iconGeometry: 80x80+0+0' -e /bin/su - qroot &
