#!/bin/ksh
################################################################################
#                   @(#)Copyright (c) 1997 William R. Quayle                   #
#                             All Rights Reserved                              #
################################################################################
#                                                                              #
# This is free software.  It comes  with absolutely  NO WARRENTY  expressed or #
# implied.                                                                     #
#                            USE AT YOUR OWN RISK!                             #
#                                                                              #
# Permission is granted to use, modify, and distribute copies of this software #
# software  provided  the following conditions are met:                        #
#                                                                              #
#      1) that that the above copyright notice and this notice                 #
#         are preserved in all copies and that due credit be given             #
#         to the author.                                                       #
#                                                                              #
#      2) that any changes to this code are clearly commented                  #
#         as such so that the author does get blamed for bugs                  #
#         other than his own.                                                  #
#                                                                              #
#      Please send copies of changes and bug-fixes to:                         #
#                                                                              #
#                             billq@technologist.com                           #
#                                                                              #
################################################################################
	typeset lpat flag str
	set -f
	if [ "$1" = -l -o "$1" = -L ]
	then
		flag=$1
		lpat=$2
		shift 2
	fi
	if [ $# -eq 0 -o $# -gt 2 ]
	then
		echo 'substring: bad argument count'
		return 1
	fi
	str=$1
	if [ "$flag" = -1 ]
	then
		str=${str#$lpat}
	elif [ "$flag" = -L ]
	then
		str=${str##$lpat}
	fi
		echo ${str%$2}
