#!/bin/ksh
################################################################################
#                   @(#)Copyright (c) 1999 William R. Quayle                   #
#                             All Rights Reserved                              #
################################################################################
#                                                                              #
# This is free software.  It comes  with absolutely  NO WARRENTY  expressed or #
# implied.                                                                     #
#                            USE AT YOUR OWN RISK!                             #
#                                                                              #
# Permission is granted to use, modify, and distribute copies of this software #
# software  provided  the following conditions are met:                        #
#                                                                              #
#      1) that that the above copyright notice and this notice                 #
#         are preserved in all copies and that due credit be given             #
#         to the author.                                                       #
#                                                                              #
#      2) that any changes to this code are clearly commented                  #
#         as such so that the author does get blamed for bugs                  #
#         other than his own.                                                  #
#                                                                              #
#      Please send copies of changes and bug-fixes to:                         #
#                                                                              #
#                             billq@technologist.com                           #
#                                                                              #
################################################################################
#!/bin/sh
echo "You are currently in `pwd`, which will be your source.
What is the target you want to sync to: \c"
read TARGET
touch $TARGET/.sdkfjlkdfjlksdfjalkdfjslkdjf >/dev/null 2>&1
if [ $? -ne 0 ]
then
	echo "You can't write to $TARGET"
	exit 1
fi
rm $TARGET/.sdkfjlkdfjlksdfjalkdfjslkdjf
for FILE in `ls`
do
  if [ ! -f ${TARGET}/$FILE ] && [ ! -d ${TARGET}/$FILE ] && [ -f $FILE ]
  then
     cp $FILE $TARGET
  else
	set -x
	ls -l $FILE
	ls -l ${TARGET}/${FILE}
	diff $FILE ${TARGET}/${FILE}|more
    echo "cp $FILE to ${TARGET}? \c"
    read yorn
    case yorn in
    ""|Y*|y*)
              cp $FILE $TARGET
    ;;
    *)
              echo "Skipping $FILE"
    ;;
    esac
  fi
done
