#!/bin/ksh
################################################################################
#                   @(#)Copyright (c) 1997 William R. Quayle                   #
#                             All Rights Reserved                              #
################################################################################
#                                                                              #
# This is free software.  It comes  with absolutely  NO WARRENTY  expressed or #
# implied.                                                                     #
#                            USE AT YOUR OWN RISK!                             #
#                                                                              #
# Permission is granted to use, modify, and distribute copies of this software #
# software  provided  the following conditions are met:                        #
#                                                                              #
#      1) that that the above copyright notice and this notice                 #
#         are preserved in all copies and that due credit be given             #
#         to the author.                                                       #
#                                                                              #
#      2) that any changes to this code are clearly commented                  #
#         as such so that the author does get blamed for bugs                  #
#         other than his own.                                                  #
#                                                                              #
#      Please send copies of changes and bug-fixes to:                         #
#                                                                              #
#                             billq@technologist.com                           #
#                                                                              #
################################################################################
# 	@(#) timinit.sh - initialization for timesheet programs
#	@(#) Use: . timinit
#	@(#) Written: February, 1986 - Rachel Peirce
#
#	Last Modification:
#	D. Joggerst	5/5/88	Add variables "prgmpath" and "FCSBIN" and update
#			PATH
#	R. Peirce	12/11/89 prgmpath is now /usr/local/bin, remove FCSBIN;
#				get basepath from file (network partition)
#
prgmpath=/usr/local/bin			# executable program directory
INNAME=pets/t				# default prefix for input file
OUTF=pets/t				# default output file
OTF=pets/o				# overtime file
FINAL=pets/tp				# prefix for final output file
OTFINAL=pets/of				# prefix for final overtime file
OTH=/usr/local/adm/overtime.trf		# troff header file for overtime
TIMEDATA=/usr/local/adm/timedata	# user data file
WEEKEND=/usr/local/adm/weekending	# weekending date
SERVERS=/usr/local/adm/servers		# servers from which to collect data
DEPTDATA=/usr/local/adm/deptdata	# info about departments
OT_TROFF_FORMAT=/usr/local/adm/overtime.trf  # troff overtime formater file for printit
export OT_TROFF_FORMAT
TAPEDEF=0				# default tape drive
ERROR=1					# exit code for error
ONTAPE=ris				# prefix for putting on tape
MASTSERV=thor				# server on which create tape
userdata=n
infile=n
restart=n
outfile=n
wkend=n					# if not reset, figure out current date
dept=n
machid=n
login=n
chkopt="-q"				# default - quiet option for chkuser
tslogin=timeshee			# login of timesheet administrator
PATH=$PATH:$prgmpath
export PATH

case $0 in
ksh) alias echo=print;;
esac
