#!/bin/ksh
################################################################################
#                   @(#)Copyright (c) 1997 William R. Quayle                   #
#                             All Rights Reserved                              #
################################################################################
#                                                                              #
# This is free software.  It comes  with absolutely  NO WARRENTY  expressed or #
# implied.                                                                     #
#                            USE AT YOUR OWN RISK!                             #
#                                                                              #
# Permission is granted to use, modify, and distribute copies of this software #
# software  provided  the following conditions are met:                        #
#                                                                              #
#      1) that that the above copyright notice and this notice                 #
#         are preserved in all copies and that due credit be given             #
#         to the author.                                                       #
#                                                                              #
#      2) that any changes to this code are clearly commented                  #
#         as such so that the author does get blamed for bugs                  #
#         other than his own.                                                  #
#                                                                              #
#      Please send copies of changes and bug-fixes to:                         #
#                                                                              #
#                             billq@technologist.com                           #
#                                                                              #
################################################################################
HOSTS="ih4ehz ih4sh ih4elab ih4ehw ih4epd ih4ehwa"
> /usr/add-on/adm/lib/tapestat
for i in $HOSTS
do
	echo "
-------------------------------
Checking tape drive on $i
-------------------------------
">>/usr/add-on/adm/lib/tapestat
	case $i in
	ih4ehz)	TAPE=/dev/nrst1	;;
	ih4ehw)	TAPE=/dev/nrsmt0	;;
	ih4epd)	TAPE=/dev/nrsmt0	;;
	ih4ehwa)	TAPE=/dev/nrsmt0	;;
	ih4elab)	TAPE=/dev/nrst1	;;
	ih4sh)	TAPE=/dev/nrst0	;;
	esac

	ping $i 1 > /dev/null 2>&1
	if [ $? = 0 ]
	then
		rsh $i mt -f $TAPE stat >> /usr/add-on/adm/lib/tapestat 2>&1
	fi
done
mail billq < /usr/add-on/adm/lib/tapestat
