#!/bin/ksh
HOSTNAME=`hostname`
RHOST=$2
REMOTE="rsh $RHOST -l root"
xhost +$RHOST >/dev/null 2>&1
case $1 in
media.run)
	/usr/bin/X11/xmessage -nearmouse -timeout 10 "Generating media report... stand by."
	/bin/echo -n "

Media report for SSD Epoch Backup System $RHOST on "> /tmp/media.rept.$$
	date >> /tmp/media.rept.$$


	echo "
List of active media.  These tapes should be present in the stackers at this time.
" >> /tmp/media.rept.$$
	$REMOTE "/usr/epoch/EB/bin/ebreport media -active"|grep 8mm|grep -v Rotations|awk '{print $7}'|sort|/usr/5bin/pr -5 -a -t -l10 >>/tmp/media.rept.$$
	/usr/bin/X11/xmessage -nearmouse -timeout 10 "Almost done... be patient."
	echo "

This is a list of those tapes that can be put offsite:
">> /tmp/media.rept.$$
	$REMOTE "/usr/epoch/EB/bin/ebreport media"|grep 8mm|grep -v '\*'|grep -v Primary|awk '{print $7}'|sort|/usr/5bin/pr -a -3 -l20 -t>>/tmp/media.rept.$$
	echo "

 All other tapes can be recycled
 
 This report will be printed to the default printer.">>/tmp/media.rept.$$
	lpr /tmp/media.rept.$$
	/usr/bin/X11/xmessage -nearmouse -file /tmp/media.rept.$$
	#textedit /tmp/media.rept.$$
	rm /tmp/media.rept.$$
;;
listbkup)
	$REMOTE "/usr/epoch/EB/bin/ebbackup -L"> /tmp/xts.out.$$
	/usr/bin/X11/xmessage -nearmouse -file /tmp/xts.out.$$
	rm /tmp/xts.out.$$
;;
killbkup)
	$REMOTE "/usr/epoch/EB/bin/ebbackup -D"> /tmp/xts.out.$$
	/usr/bin/X11/xmessage -nearmouse -file /tmp/xts.out.$$
	rm /tmp/xts.out.$$
;;
xebadmin)
	$REMOTE "export DISPLAY=${HOSTNAME}:0;/usr/epoch/EB/bin/xebadmin"
;;
xebrecover)
	$REMOTE "export DISPLAY=${HOSTNAME}:0;/usr/epoch/EB/bin/xebrecover"
;;
*)
	xterm -e $*
;;
esac
